### ISSUE TITLE
Test with Yolo3 80 Classes

### ISSUE THREAD

**Issue by bishoymoussa** [Kammerlo/keras-yolo3-serving#2]
I want to try to use tfserving with Yolo3 80 classes Implementation : https://github.com/qqwweee/keras-yolo3 and I want to know what changes I should make

**Comment by Kammerlo** [comment]
Hi,

I'm glad that the repository is useful for other people. 👍 
In my ReadMe I provided the pretrained weights for the yolo. You can download them from my [GoogleDrive](https://drive.google.com/open?id=1RnA-N7z-rEKEPF6X29TQX34e_b3Gr93w).

To run the export to TFServing you need to use this [config file](https://github.com/Kammerlo/keras-yolo3-serving/blob/master/zoo/config_voc.json) .

Hope it helps you to achieve what you're trying to do.

Best,
Thomas

**Comment by Kammerlo** [comment]
Since I haven't heard anything else I'm going to close this issue. If you have anything else, just let me know.
